/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectomecanica;

import javax.swing.JButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author sofi_iikan_faber_liz_¿jhosep?
 */
public class InterfazG extends javax.swing.JFrame {

    /**
     * Creates new form InterfazG
     */
    public InterfazG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTextoIncognitas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jaceleracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jvelocidadinicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jvelocidadfinal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtiempo = new javax.swing.JTextField();
        jposicionfinal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jposicioninicial = new javax.swing.JTextField();
        Bgraficarvt = new javax.swing.JButton();
        Bgraficarxt = new javax.swing.JButton();
        bCalcular = new javax.swing.JButton();
        Blimpiar = new javax.swing.JButton();
        TAceleracion = new javax.swing.JLabel();
        jRAceleracion = new javax.swing.JTextField();
        jRVelocidadInicial = new javax.swing.JTextField();
        jRVelocidadFinal = new javax.swing.JTextField();
        jRTiempo = new javax.swing.JTextField();
        jRPosicionInicial = new javax.swing.JTextField();
        jRPosicionFinal = new javax.swing.JTextField();
        TVelocidadInicial = new javax.swing.JLabel();
        TVelocidadFinal = new javax.swing.JLabel();
        TTiempo = new javax.swing.JLabel();
        TPosicionInicial = new javax.swing.JLabel();
        TPosicionFinal = new javax.swing.JLabel();
        jPanelGraficar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelResultados = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(190, 235, 235));

        jLabelTextoIncognitas.setFont(new java.awt.Font("Gabriola", 3, 28)); // NOI18N
        jLabelTextoIncognitas.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTextoIncognitas.setText("Ingrese los datos que tiene del MRUA para calcular la incógnita");

        jLabel4.setText("Aceleracion:");

        jaceleracion.setToolTipText("");
        jaceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaceleracionActionPerformed(evt);
            }
        });

        jLabel5.setText("Velocidad Iinicial:");

        jvelocidadinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvelocidadinicialActionPerformed(evt);
            }
        });

        jLabel6.setText("Velocidad final:");

        jLabel7.setText("Tiempo:");

        jLabel8.setText("Posicion final:");

        jLabel9.setText("Posicion inicial:");

        Bgraficarvt.setText("Velocidad vs Tiempo");
        Bgraficarvt.setEnabled(false);
        Bgraficarvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgraficarvtActionPerformed(evt);
            }
        });

        Bgraficarxt.setText("Posición Vs Tiempo");
        Bgraficarxt.setEnabled(false);
        Bgraficarxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgraficarxtActionPerformed(evt);
            }
        });

        bCalcular.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bCalcular.setForeground(new java.awt.Color(0, 153, 51));
        bCalcular.setText("Calcular");

        Blimpiar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Blimpiar.setForeground(new java.awt.Color(204, 0, 0));
        Blimpiar.setText("Cancelar");
        Blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimpiarActionPerformed(evt);
            }
        });

        TAceleracion.setText("Aceleracion: ");

        jRAceleracion.setEditable(false);
        jRAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAceleracionActionPerformed(evt);
            }
        });

        jRVelocidadInicial.setEditable(false);

        jRVelocidadFinal.setEditable(false);
        jRVelocidadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRVelocidadFinalActionPerformed(evt);
            }
        });

        jRTiempo.setEditable(false);
        jRTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTiempoActionPerformed(evt);
            }
        });

        jRPosicionInicial.setEditable(false);

        jRPosicionFinal.setEditable(false);
        jRPosicionFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRPosicionFinalActionPerformed(evt);
            }
        });

        TVelocidadInicial.setText("Velocidad inicial:");

        TVelocidadFinal.setText("Velocidad final:");

        TTiempo.setText("Tiempo:");

        TPosicionInicial.setText("Posicion inicial:");

        TPosicionFinal.setText("Posicion final:");

        jPanelGraficar.setBackground(new java.awt.Color(255, 204, 153));
        jPanelGraficar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jLabel16.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("GRAFICAR: ");

        javax.swing.GroupLayout jPanelGraficarLayout = new javax.swing.GroupLayout(jPanelGraficar);
        jPanelGraficar.setLayout(jPanelGraficarLayout);
        jPanelGraficarLayout.setHorizontalGroup(
            jPanelGraficarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGraficarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(277, 277, 277))
        );
        jPanelGraficarLayout.setVerticalGroup(
            jPanelGraficarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGraficarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelDatos.setBackground(new java.awt.Color(255, 204, 153));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102)));
        jPanelDatos.setForeground(new java.awt.Color(255, 153, 102));

        jLabel17.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("DATOS: ");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelResultados.setBackground(new java.awt.Color(255, 204, 153));
        jPanelResultados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102)));

        jLabel18.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("RESULTADOS:");

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(96, 96, 96))
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bgraficarxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bgraficarvt)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Blimpiar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jposicioninicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jposicionfinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jaceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jvelocidadinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jvelocidadfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TPosicionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TVelocidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TVelocidadInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TPosicionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRPosicionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRPosicionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRVelocidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRVelocidadInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTextoIncognitas)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTextoIncognitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jaceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jvelocidadinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jvelocidadfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jposicioninicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jposicionfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCalcular)
                            .addComponent(Blimpiar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TAceleracion)
                            .addComponent(jRAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRVelocidadInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TVelocidadInicial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRVelocidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TVelocidadFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TTiempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRPosicionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TPosicionInicial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRPosicionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TPosicionFinal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanelGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bgraficarxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bgraficarvt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 820, 640));

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(135, 135, 14)));

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(125, 125, 30));
        jLabelTitulo.setText("El caos rectilíneo del Sr. MRUA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BgraficarvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgraficarvtActionPerformed

    }//GEN-LAST:event_BgraficarvtActionPerformed

    private void jaceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaceleracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaceleracionActionPerformed

    private void jvelocidadinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvelocidadinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvelocidadinicialActionPerformed

    private void jRPosicionFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRPosicionFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRPosicionFinalActionPerformed

    private void jRAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAceleracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRAceleracionActionPerformed

    private void jRVelocidadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRVelocidadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRVelocidadFinalActionPerformed

    private void jRTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTiempoActionPerformed

    private void BgraficarxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgraficarxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BgraficarxtActionPerformed

    private void BlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimpiarActionPerformed
        // TODO add your handling code here:
        this.jaceleracion.setText("");
        this.jtiempo.setText("");
        this.jvelocidadinicial.setText("");
        this.jvelocidadfinal.setText("");
        this.jposicioninicial.setText("");
        this.jposicionfinal.setText("");
        this.jRAceleracion.setText("");
        this.jRTiempo.setText("");
        this.jRVelocidadInicial.setText("");
        this.jRVelocidadFinal.setText("");
        this.jRPosicionInicial.setText("");
        this.jRPosicionFinal.setText("");
    }//GEN-LAST:event_BlimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bgraficarvt;
    public javax.swing.JButton Bgraficarxt;
    private javax.swing.JButton Blimpiar;
    private javax.swing.JLabel TAceleracion;
    private javax.swing.JLabel TPosicionFinal;
    private javax.swing.JLabel TPosicionInicial;
    private javax.swing.JLabel TTiempo;
    private javax.swing.JLabel TVelocidadFinal;
    private javax.swing.JLabel TVelocidadInicial;
    private javax.swing.JButton bCalcular;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTextoIncognitas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelGraficar;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JTextField jRAceleracion;
    private javax.swing.JTextField jRPosicionFinal;
    private javax.swing.JTextField jRPosicionInicial;
    private javax.swing.JTextField jRTiempo;
    private javax.swing.JTextField jRVelocidadFinal;
    private javax.swing.JTextField jRVelocidadInicial;
    private javax.swing.JTextField jaceleracion;
    private javax.swing.JTextField jposicionfinal;
    private javax.swing.JTextField jposicioninicial;
    private javax.swing.JTextField jtiempo;
    private javax.swing.JTextField jvelocidadfinal;
    private javax.swing.JTextField jvelocidadinicial;
    // End of variables declaration//GEN-END:variables

    public void agregarListenerBotonCalcular(ActionListener listener) {
        // TODO add your handling code here:
        bCalcular.addActionListener(listener);
    }

    public void agregarListenerBgreficarxt(ActionListener listener) {
        Bgraficarxt.addActionListener(listener);
    }

    public void agregarListenerBgreficarvt(ActionListener listener) {
        Bgraficarvt.addActionListener(listener);
    }

    public Double strToDouble(String texto) {
        if (texto.isEmpty()) {
            return null; // Devuelve null si el campo está vacío
        }
        // Intenta convertir el texto a Double
        try {
            return Double.valueOf(texto);
        } catch (NumberFormatException e) {
            return null;
        }
    }
    public String DoubleToString(Double D){
        if(D == null ) return "";
        return D + "";
    }
    public Double getJaceleracion() {
        return strToDouble(jaceleracion.getText());
    }

    public Double getJposicionfinal() {
        return strToDouble(jposicionfinal.getText());
    }

    public Double getJposicioninicial() {
        return strToDouble(jposicioninicial.getText());
    }

    public Double getJtiempo() {
        return strToDouble(jtiempo.getText());
    }

    public Double getJvelocidadfinal() {
        return strToDouble(jvelocidadfinal.getText());
    }

    public Double getJvelocidadinicial() {
        return strToDouble(jvelocidadinicial.getText());
    }

    public void setjRAceleracion(Double aceleracion) {
        
        jRAceleracion.setText(DoubleToString(aceleracion));
    }

    public void setjRTiempo(Double tiempo) {
        jRTiempo.setText(DoubleToString(tiempo));
    }

    public void setjRVelocidadInicial(Double velocidadI) {
        jRVelocidadInicial.setText(DoubleToString(velocidadI));
    }

    public void setjRAVelocidadFinal(Double velocidadF) {
        jRVelocidadFinal.setText(DoubleToString(velocidadF));
    }

    public void setjRPosicionInicial(Double posicionI) {
        jRPosicionInicial.setText(DoubleToString(posicionI));
    }

    public void setjRPosicionFinal(Double posicionF) {
        jRPosicionFinal.setText(DoubleToString(posicionF));
    }

}
